baseURL = 'https://azurestorage.com/'
languageCode = "en-us"
title = "Azure Storage"
theme = "book"
publishdir = "../docs/"

[params]
  BookLogo = "/images/azure-icon.png"

[markup.goldmark.renderer]
  unsafe = true