baseURL = 'https://azure.github.io/Storage/'
languageCode = "en-us"
title = "Azure Storage"
theme = "book"
publishdir = "../docs/"

[params]
  BookLogo = "/Storage/images/azure-icon.png"

[markup.goldmark.renderer]
  unsafe = true